from . import student_details
from . import faculty_details
from . import clg_area_details
from . import admission_details
from . import placement_details
from . import course_details
from . import class_details
from . import student_data_details
from . import collage_information
